language: php

php:
  - 7.2
  - 7.3
  - 7.4

env:
  - CORCEL=^4.0
  - CORCEL=^5.0

matrix:
  exclude:
    - php: 7.2
      env: CORCEL=^5.0

dist: trusty

addons:
  apt:
    packages:
    - unzip
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6

before_script:
  - unzip tests/config/database.sql.zip -d tests/config/
  - mysql -u root -e "create database corcel_acf;"
  - mysql -u root corcel_acf < tests/config/database.sql

before_install:
  - composer self-update
  - composer require corcel/corcel:$CORCEL --no-interaction --no-update

install:
  - composer install --prefer-dist --no-interaction --no-suggest

script:
  - mkdir -p build/logs
  - ./vendor/bin/phpunit
